######################################################################
# Automatically generated by qmake (2.01a) Fr. Feb 5 22:32:35 2016
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

POPPLER = poppler-qt4

unix {
    CONFIG += link_pkgconfig
    PKGCONFIG += $$POPPLER
}

# Input
SOURCES += test.cpp
